// hpsdr_p1.c - Minimal openHPSDR Protocol 1 IQ streamer and command interface
// Command and discovery code based on hpsdrsim.c, the piHPSDR project's HPSDR simulator
// which is licensed as GPL 2.0
//
// Code generated by copilot AI as a demo only ... good luck!  Mike/KB2ML

#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <pthread.h>
#include "cw.h"

#define HPSDR_PORT 1024
#define HPSDR_PKT_SIZE 1032
#define SAMPLES_PER_PACKET 126

static int hpsdr_sock = -1;
static struct sockaddr_in stream_dest;
static volatile int client_active = 0;
static volatile int running = 0;
static uint32_t tx_seq = 0;
static pthread_t poll_thread;

// IQ accumulation buffer for 126 samples (48kHz)
static double iq_buf_i[SAMPLES_PER_PACKET];
static double iq_buf_q[SAMPLES_PER_PACKET];
static int iq_buf_count = 0;
static double hpsdr_iq_gain = 1.0;  // <<<<< add gain to I and Q data going out

extern void radio_set_tx(int tx_on);
extern void radio_tune_to(uint32_t f);   // same call hamlib.c "F" command uses
extern int freq_hdr;   // hamlib.c "F" command and this file's EP2 handler both retune via radio_tune_to()
extern int in_tx;      // read-only here - radio_set_tx() owns writing it

// Last non-zero RX1 (DDC0) frequency seen in EP2 C&C addr 0x02. Persisted
// because the client's C&C round-robin only populates this slot once every
// several frames - it's zero the rest of the time.
static uint32_t last_rx_freq = 0;

// Last non-zero TX VFO frequency seen in EP2 C&C addr 0x01. In SDR Console
// this is the operator's selected signal ("RX 1"); in apps like SPARK SDR
// it's always the spectrum center, same as last_rx_freq.
static uint32_t last_tx_freq = 0;

// --- Packet construction & inline transmission ------------------------------

static void build_and_send_packet(void)
{
    uint8_t pkt[HPSDR_PKT_SIZE];
    memset(pkt, 0, sizeof(pkt));

    // EP6 Header
    pkt[0] = 0xEF;
    pkt[1] = 0xFE;
    pkt[2] = 0x01;
    pkt[3] = 0x06;
    pkt[4] = (tx_seq >> 24) & 0xFF;
    pkt[5] = (tx_seq >> 16) & 0xFF;
    pkt[6] = (tx_seq >>  8) & 0xFF;
    pkt[7] =  tx_seq        & 0xFF;

    // Use current sequence to derive C&C address cadence, then increment once per packet
    uint32_t seq_for_cc = tx_seq++;

    // Two 512-byte frames
    for (int frame = 0; frame < 2; frame++) {
        uint8_t *fp = pkt + 8 + frame * 512;

        // Sync bytes
        fp[0] = 0x7F; fp[1] = 0x7F; fp[2] = 0x7F;

        // C&C control byte:
        // bit0 = MOX (TX flag), bits[5:1] = C0 address 0..31
        int cc_addr = (int)((seq_for_cc * 2 + frame) & 0x1F);
        fp[3] = (uint8_t)((cc_addr << 1) | (in_tx ? 1 : 0));

        // Fill control payload bytes [4..7] by C0 address
        // Keep this minimal but consistent with your current behavior.
        switch (cc_addr) {
            case 0:
                // Receiver 1 frequency (network byte order)
                fp[4] = (freq_hdr >> 24) & 0xFF;
                fp[5] = (freq_hdr >> 16) & 0xFF;
                fp[6] = (freq_hdr >>  8) & 0xFF;
                fp[7] =  freq_hdr        & 0xFF;
                break;

            case 1:
                // Temperature (bits 31:16) / Forward Power (bits 15:0) on
                // real hardware. No such sensor here, so zero. Sample rate
                // has no readback field anywhere in EP6 - it's host-
                // requested only (EP2 addr 0, data bits [25:24]), and
                // minibitx doesn't parse that request, so the SDR app's
                // connection must be configured to match sound.c's
                // SAMPLE_RATE by hand.
                fp[4] = 0x00;
                fp[5] = 0x00;
                fp[6] = 0x00;
                fp[7] = 0x00;
                break;

            case 2:
                // Mirror RX frequency here too to satisfy clients that watch addr 2 traffic
                fp[4] = (freq_hdr >> 24) & 0xFF;
                fp[5] = (freq_hdr >> 16) & 0xFF;
                fp[6] = (freq_hdr >>  8) & 0xFF;
                fp[7] =  freq_hdr        & 0xFF;
                break;

            default:
                // Leave zeros for unimplemented C&C addresses
                fp[4] = 0x00;
                fp[5] = 0x00;
                fp[6] = 0x00;
                fp[7] = 0x00;
                break;
        }

        // 63 IQ samples per frame
        for (int s = 0; s < 63; s++) {
            int idx = frame * 63 + s;
            uint8_t *sp = fp + 8 + s * 8;

            int32_t i_val = (int32_t)(iq_buf_i[idx] * 559240.0);
            if (i_val > 8388607) i_val = 8388607;
            if (i_val < -8388608) i_val = -8388608;

            int32_t q_val = (int32_t)(iq_buf_q[idx] * 559240.0);
            if (q_val > 8388607) q_val = 8388607;
            if (q_val < -8388608) q_val = -8388608;

            // Pack I (24-bit signed)
            sp[0] = (i_val >> 16) & 0xFF;
            sp[1] = (i_val >>  8) & 0xFF;
            sp[2] =  i_val        & 0xFF;

            // Pack Q (24-bit signed)
            sp[3] = (q_val >> 16) & 0xFF;
            sp[4] = (q_val >>  8) & 0xFF;
            sp[5] =  q_val        & 0xFF;

            // Mic sample (unused)
            sp[6] = 0;
            sp[7] = 0;
        }
    }

    if (client_active) {
        sendto(hpsdr_sock, pkt, sizeof(pkt), 0,
               (struct sockaddr *)&stream_dest, sizeof(stream_dest));
    }
}

// --- Main Audio Thread Hook -------------------------------------------------

// Called continuously with 48kHz samples from the RX processing chain.
// No filtering or decimation required; just gain and packetization.
//
// This is sound.c's copy of the IQ for the HPSDR/UDP stream only - it
// knows nothing about usb_gadget.c, which sound.c feeds separately from
// its own copy. A no-op whenever no Protocol 1 client is connected.
void hpsdr_send_iq(double *i_samples, double *q_samples, int n)
{
    if (!client_active || hpsdr_sock < 0) return;

    for (int k = 0; k < n; k++) {
        iq_buf_i[iq_buf_count] = i_samples[k] * hpsdr_iq_gain;
        iq_buf_q[iq_buf_count] = q_samples[k] * hpsdr_iq_gain;
        iq_buf_count++;

        if (iq_buf_count >= SAMPLES_PER_PACKET) {
            build_and_send_packet();
            iq_buf_count = 0;
        }
    }
}

// --- Command and Discovery (Background Thread) ------------------------------
//
// Inbound parsing below is modeled on hpsdrsim.c (the piHPSDR project's
// HPSDR hardware simulator - https://github.com/g0orx/pihpsdr), a mature,
// widely-used reference for exactly this side of the protocol: standing
// in for real HPSDR/Metis hardware so client apps can connect to
// something that isn't a physical radio. Earlier testing against a
// looser version of this file (no exact-length checks on inbound
// packets) saw EP2 frames decode to nonsensical, wildly varying C&C
// addresses (0x3A and similar) with the MOX bit seemingly random - the
// strict per-packet-type length checks below are hpsdrsim's own
// safeguard against exactly that ("processing an invalid packet is too
// dangerous - skip it", to quote its comments). That turned out to be
// necessary but not sufficient: two more bugs surfaced even with strict
// lengths in place - reading MOX from every address (matching
// hpsdrsim.c literally) still picked up unrelated register data as
// spurious PTT activity, and comparing the network's want_tx against
// the shared in_tx (which the local key in cw.c also writes) let a
// stale, already-unchanged network value look like a fresh request the
// moment the key released TX, latching it on permanently. See the
// cc_addr and net_mox comments in process_ep2_frame() for both fixes.
// Tracks the host->radio EP2 sequence number (bytes 4-7 of every
// 1032-byte packet), purely as a diagnostic - a gap here means a
// dropped or reordered UDP datagram, not an anomaly in what the SDR
// app is sending. Never drops a packet over it, just logs. Bench
// testing (with SDR Console) showed real, harmless reordering of
// adjacent packets (359,360,361 sent, arriving as 360,359,361) - normal
// on a network, not something to fix here, but useful to know isn't
// packet corruption.
static uint32_t last_ep2_seq = 0;
static int have_ep2_seq = 0;

// The network's own last-seen MOX bit, tracked independently of in_tx
// (which cw.c's local key can also change). Needed for a real bug found
// in testing: with a local key held, in_tx gets set by the key, not the
// network - so once the key's hang timer releases TX (in_tx back to 0),
// the very next EP2 packet carrying whatever the network happened to
// still be sending (even an unchanged, already-stale want_tx=1 SDR
// Console had been sending the whole time) looks exactly like a brand
// new request, because it now differs from the just-released in_tx.
// One key press then latched TX on permanently, through every further
// key press, because of this. net_mox lets us tell "the network's
// intent just changed" apart from "in_tx changed for an unrelated
// reason (the local key)" - only a real change in net_mox should ever
// trigger an action here.
static int net_mox = 0;

// Processes ONE 512-byte EP2 sub-frame. fp points at the frame's sync
// bytes (0x7F 0x7F 0x7F) - offset buf+8 for the first sub-frame and
// buf+8+512 for the second, matching both build_and_send_packet()'s own
// outbound layout and hpsdrsim.c's inbound offsets (buffer+11/buffer+523
// relative to the full packet - i.e. the same 8-byte header + 3 sync
// bytes before the C0 byte at fp[3]).
static void process_ep2_frame(uint8_t *fp)
{
    if (fp[0] != 0x7F || fp[1] != 0x7F || fp[2] != 0x7F) return;

    // C&C register this frame carries - bits 6:1 of C0 (a 6-bit address,
    // 0-63; bit 7 is reserved and must not be folded into it). Matches
    // build_and_send_packet()'s own outbound addressing and the
    // Hermes-Lite2 protocol documentation.
    int cc_addr = (fp[3] >> 1) & 0x3F;

    // addr 0x01 = TX VFO frequency (operator's selected signal in SDR
    // Console; spectrum center in apps like SPARK SDR).
    if (cc_addr == 0x01) {
        uint32_t freq = ((uint32_t)fp[4] << 24) | ((uint32_t)fp[5] << 16) |
                         ((uint32_t)fp[6] <<  8) |  (uint32_t)fp[7];
        if (freq) last_tx_freq = freq;
    }

    // addr 0x02 = RX1 (DDC0) frequency.
    if (cc_addr == 0x02) {
        uint32_t freq = ((uint32_t)fp[4] << 24) | ((uint32_t)fp[5] << 16) |
                         ((uint32_t)fp[6] <<  8) |  (uint32_t)fp[7];
        if (freq) last_rx_freq = freq;
    }

    // MOX (PTT) is only acted on from C&C register (address) 0. The
    // real protocol - and hpsdrsim.c, which reads bit0 of C0 as
    // `frame[0] & 1` before ever looking at the address - treats MOX as
    // live on every frame regardless of address; testing that literally
    // (removing this same restriction) reintroduced spurious activity
    // even with strict packet-length validation in place, so it's kept
    // here as a real, bench-confirmed requirement against these
    // clients, not just a workaround for a since-fixed parsing bug.
    if (cc_addr != 0x00)
        return;     
    
    int want_tx = (fp[3] & 0x01) ? 1 : 0;
    int net_mox_changed = (want_tx != net_mox);
    net_mox = want_tx;

    // Defer to the local key completely while it's holding TX - see
    // cw.c. net_mox is still kept current above (rather than skipped
    // entirely) specifically so a value the network was already sending
    // before the key took over doesn't look like a fresh edge the
    // moment it releases - see the net_mox comment above for why that
    // matters.
    if (cw_tx_active())
        return;

    if (net_mox_changed && want_tx != in_tx) {
        if (want_tx) {
            // Retune to the operator's TX frequency before keying. Fall
            // back to the RX frequency if addr 0x01 was never received.
            uint32_t tx_freq = last_tx_freq ? last_tx_freq : last_rx_freq;
            if (tx_freq && tx_freq != (uint32_t)freq_hdr)
                radio_tune_to(tx_freq);
        }
        radio_set_tx(want_tx);
        printf("hpsdr: MOX -> %s\n", want_tx ? "TX on" : "TX off");
    }
}
    
static void handle_command(uint8_t *buf, int len, struct sockaddr_in *sender)
{
    // Live frequency control lives exclusively in hamlib.c's rigctld-
    // compatible "F" command; this file only reports freq_hdr back as
    // outbound telemetry (see build_and_send_packet()).

    if (len < 4) return;
    if (buf[0] != 0xEF || buf[1] != 0xFE) return;

    switch (buf[2]) {
    case 0x02:  // Discovery request - real clients always send exactly
                // 63 bytes (see hpsdrsim.c); anything else isn't a
                // genuine discovery packet and isn't worth answering.
         {
            if (len != 63) break;

            uint8_t reply[64];
            memset(reply, 0, sizeof(reply));

            reply[0] = 0xEF;
            reply[1] = 0xFE;
            reply[2] = 0x02;

            // 0x00 = available, 0x02 = in-use by another client
            int same_client =
                (client_active &&
                 sender->sin_addr.s_addr == stream_dest.sin_addr.s_addr &&
                 sender->sin_port        == stream_dest.sin_port);

            reply[3] = (client_active && !same_client) ? 0x02 : 0x00;

            // MAC + board/protocol identifiers (keep your current values for now)
            reply[4]  = 0x00; reply[5]  = 0x1C; reply[6]  = 0xC0;
            reply[7]  = 0xA2; reply[8]  = 0x22; reply[9]  = 0x5B;
            reply[10] = 0x88; // board type: Hermes Lite2 (closest honest match)
            reply[11] = 0x25; // protocol version

            sendto(hpsdr_sock, reply, sizeof(reply), 0,
                   (struct sockaddr *)sender, sizeof(*sender));
        }
        break;

    case 0x04:  // Start / stop streaming - always exactly 64 bytes.
        {
            if (len != 64) break;

            int start = ((buf[3] & 0x01) != 0) || (buf[3] != 0x00);
        
            if (start) {
                int same_dest =
                    client_active &&
                    sender->sin_addr.s_addr == stream_dest.sin_addr.s_addr &&
                    sender->sin_port        == stream_dest.sin_port;

                // Reply to the sender's actual address:port - clients
                // receive the EP6 IQ stream on their own ephemeral port,
                // not HPSDR_PORT (1024, which is only where they send
                // commands to us).
                if (!same_dest) {
                    stream_dest = *sender;
                    tx_seq = 0;
                    iq_buf_count = 0;
                    printf("hpsdr: streaming STARTED cmd=%u to %s:%d\n",
                           (unsigned)buf[3], inet_ntoa(stream_dest.sin_addr), ntohs(stream_dest.sin_port));
                } else {
                    // repeated START from same client: keep streaming, do not reset seq/buffer
                    stream_dest = *sender;   // refresh anyway
                }

                client_active = 1;
            } else {
                client_active = 0;
                printf("hpsdr: streaming STOPPED cmd=%u\n", (unsigned)buf[3]);
            }
        }
        break;

    
        case 0x01:  // EP2 host commands - always exactly 1032 bytes (8-byte
                // header + two 512-byte sub-frames). Anything else is a
                // torn or malformed packet, not real data - trying to
                // parse it anyway (the previous "accept a partial
                // packet" behavior) is what let nonsensical C&C
                // addresses through in the first place.
        {
            if (len != HPSDR_PKT_SIZE) break;
            uint32_t seq = ((uint32_t)buf[4] << 24) | ((uint32_t)buf[5] << 16) |
                           ((uint32_t)buf[6] <<  8) |  (uint32_t)buf[7];
            if (have_ep2_seq && seq != last_ep2_seq + 1) {
                printf("hpsdr: EP2 seq gap: expected %u, got %u\n",
                      last_ep2_seq + 1, seq);
             }
            last_ep2_seq = seq;
            have_ep2_seq = 1;

            process_ep2_frame(buf + 8);
            process_ep2_frame(buf + 8 + 512);

            // Follow the SDR app's tuning while receiving.
            if (!in_tx && last_rx_freq && last_rx_freq != (uint32_t)freq_hdr) {
                radio_tune_to(last_rx_freq);
                printf("hpsdr: remote tune -> %u Hz\n", last_rx_freq);
            }
        }
        break;

    default:
        break;
    }
}

static void *hpsdr_poll_thread(void *arg)
{
    (void)arg;
    uint8_t buf[2048];
    struct sockaddr_in sender;
    socklen_t sender_len;

    while (running) {
        sender_len = sizeof(sender);
        int n = recvfrom(hpsdr_sock, buf, sizeof(buf), 0,
                         (struct sockaddr *)&sender, &sender_len);
        if (n > 0) {
            handle_command(buf, n, &sender);
        }
    }
    return NULL;
}

// --- Initialization API -----------------------------------------------------

int hpsdr_init(void)
{
    hpsdr_sock = socket(AF_INET, SOCK_DGRAM, 0);
    if (hpsdr_sock < 0) return -1;

    int optval = 1;
    setsockopt(hpsdr_sock, SOL_SOCKET, SO_REUSEADDR, &optval, sizeof(optval));
    setsockopt(hpsdr_sock, SOL_SOCKET, SO_BROADCAST, &optval, sizeof(optval));

    struct sockaddr_in addr;
    memset(&addr, 0, sizeof(addr));
    addr.sin_family = AF_INET;
    addr.sin_port = htons(HPSDR_PORT);
    addr.sin_addr.s_addr = htonl(INADDR_ANY);

    if (bind(hpsdr_sock, (struct sockaddr *)&addr, sizeof(addr)) < 0) {
        close(hpsdr_sock);
        hpsdr_sock = -1;
        return -1;
    }

    struct timeval tv = { .tv_sec = 0, .tv_usec = 200000 };
    setsockopt(hpsdr_sock, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv));

    running = 1;
    return 0;
}

void hpsdr_stop(void)
{
    running = 0;
    client_active = 0;
    
    if (hpsdr_sock >= 0) {
        close(hpsdr_sock);
        hpsdr_sock = -1;
    }
}

int hpsdr_is_connected(void)
{
    return client_active;
}

void hpsdr_poll(void)
{
    static int started = 0;
    if (!started && running) {
        pthread_create(&poll_thread, NULL, hpsdr_poll_thread, NULL);
        started = 1;
    }
}
