// hpsdr_p1.c - Minimal openHPSDR Protocol 1 IQ streamer for sBitx
//
// Sends baseband IQ from sBitx to a Protocol 1 SDR client on our network.
// Packets are sent inline without flow control or mutexes.
// Input is 48k IQ samples per second, delivered by sound.c - this file has
// no ALSA or USB gadget dependency of its own; usb_gadget.c is an entirely
// separate consumer of the same IQ, fed directly by sound.c.
// I and Q values received are scaled up to make SDR apps happier.
//
// Frequency and mode control live entirely in the rigctld-compatible
// server in hamlib.c now. This file used to parse a "remote set frequency"
// out of the inbound EP2 C&C stream (C0 address 2) and call
// radio_tune_to() directly - that path is gone, so there is exactly one
// control surface instead of two that could race each other. The one
// thing still read from the inbound stream is the MOX (PTT) bit, since
// some SDR apps key PTT through the I/Q link's C0 byte even while using
// CAT for everything else.
//
// Code generated by copilot AI as a demo only ... good luck!  Mike/KB2ML

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <pthread.h>

#define HPSDR_PORT 1024
#define HPSDR_PKT_SIZE 1032
#define SAMPLES_PER_PACKET 126

static int hpsdr_sock = -1;
static struct sockaddr_in stream_dest;
static volatile int client_active = 0;
static volatile int running = 0;
static uint32_t tx_seq = 0;
static pthread_t poll_thread;

// IQ accumulation buffer for 126 samples (48kHz)
static double iq_buf_i[SAMPLES_PER_PACKET];
static double iq_buf_q[SAMPLES_PER_PACKET];
static int iq_buf_count = 0;
static double hpsdr_iq_gain = 30.0;  // <<<<< add gain to I and Q data going out

extern void radio_set_tx(int tx_on);
extern int freq_hdr;   // read-only here - hamlib.c's "F" command owns writing it
extern int in_tx;      // read-only here - radio_set_tx() owns writing it

// --- Packet construction & inline transmission ------------------------------

static void build_and_send_packet(void)
{
    uint8_t pkt[HPSDR_PKT_SIZE];
    memset(pkt, 0, sizeof(pkt));

    // EP6 Header
    pkt[0] = 0xEF;
    pkt[1] = 0xFE;
    pkt[2] = 0x01;
    pkt[3] = 0x06;
    pkt[4] = (tx_seq >> 24) & 0xFF;
    pkt[5] = (tx_seq >> 16) & 0xFF;
    pkt[6] = (tx_seq >>  8) & 0xFF;
    pkt[7] =  tx_seq        & 0xFF;

    // Use current sequence to derive C&C address cadence, then increment once per packet
    uint32_t seq_for_cc = tx_seq++;

    // Two 512-byte frames
    for (int frame = 0; frame < 2; frame++) {
        uint8_t *fp = pkt + 8 + frame * 512;

        // Sync bytes
        fp[0] = 0x7F; fp[1] = 0x7F; fp[2] = 0x7F;

        // C&C control byte:
        // bit0 = MOX (TX flag), bits[5:1] = C0 address 0..31
        int cc_addr = (int)((seq_for_cc * 2 + frame) & 0x1F);
        fp[3] = (uint8_t)((cc_addr << 1) | (in_tx ? 1 : 0));

        // Fill control payload bytes [4..7] by C0 address
        // Keep this minimal but consistent with your current behavior.
        switch (cc_addr) {
            case 0:
                // Receiver 1 frequency (network byte order)
                fp[4] = (freq_hdr >> 24) & 0xFF;
                fp[5] = (freq_hdr >> 16) & 0xFF;
                fp[6] = (freq_hdr >>  8) & 0xFF;
                fp[7] =  freq_hdr        & 0xFF;
                break;

            case 1:
                // Basic status/sample-rate flags
                // Keep as zero for now (48k/no-overflow baseline in your prior code)
                fp[4] = 0x00;
                fp[5] = 0x00;
                fp[6] = 0x00;
                fp[7] = 0x00;
                break;

            case 2:
                // Mirror RX frequency here too to satisfy clients that watch addr 2 traffic
                fp[4] = (freq_hdr >> 24) & 0xFF;
                fp[5] = (freq_hdr >> 16) & 0xFF;
                fp[6] = (freq_hdr >>  8) & 0xFF;
                fp[7] =  freq_hdr        & 0xFF;
                break;

            default:
                // Leave zeros for unimplemented C&C addresses
                fp[4] = 0x00;
                fp[5] = 0x00;
                fp[6] = 0x00;
                fp[7] = 0x00;
                break;
        }

        // 63 IQ samples per frame
        for (int s = 0; s < 63; s++) {
            int idx = frame * 63 + s;
            uint8_t *sp = fp + 8 + s * 8;

            int32_t i_val = (int32_t)(iq_buf_i[idx] * 559240.0);
            if (i_val > 8388607) i_val = 8388607;
            if (i_val < -8388608) i_val = -8388608;

            int32_t q_val = (int32_t)(iq_buf_q[idx] * 559240.0);
            if (q_val > 8388607) q_val = 8388607;
            if (q_val < -8388608) q_val = -8388608;

            // Pack I (24-bit signed)
            sp[0] = (i_val >> 16) & 0xFF;
            sp[1] = (i_val >>  8) & 0xFF;
            sp[2] =  i_val        & 0xFF;

            // Pack Q (24-bit signed)
            sp[3] = (q_val >> 16) & 0xFF;
            sp[4] = (q_val >>  8) & 0xFF;
            sp[5] =  q_val        & 0xFF;

            // Mic sample (unused)
            sp[6] = 0;
            sp[7] = 0;
        }
    }

    if (client_active) {
        static int dbg = 0;
        if ((dbg++ % 200) == 0) {
            // THIS IS FOR DEBUG
            int32_t max_i = 0, max_q = 0;
            for (int frame = 0; frame < 2; frame++) {
                int base = 8 + frame * 512 + 8; // skip EP6 hdr + frame sync/C&C
                for (int s = 0; s < 63; s++) {
                    int off = base + s * 8;
                    int32_t i = (int32_t)((pkt[off+0] << 16) | (pkt[off+1] << 8) | pkt[off+2]);
                    int32_t q = (int32_t)((pkt[off+3] << 16) | (pkt[off+4] << 8) | pkt[off+5]);
                    if (i & 0x800000) i |= ~0xFFFFFF;
                    if (q & 0x800000) q |= ~0xFFFFFF;
                    if (abs(i) > max_i) max_i = abs(i);
                    if (abs(q) > max_q) max_q = abs(q);
                }
            }
            //printf("EP6 seq=%u maxI=%d maxQ=%d firstI=%02X%02X%02X firstQ=%02X%02X%02X\n",
               //tx_seq - 1, max_i, max_q, pkt[16], pkt[17], pkt[18], pkt[19], pkt[20], pkt[21]);
        }
        sendto(hpsdr_sock, pkt, sizeof(pkt), 0,
               (struct sockaddr *)&stream_dest, sizeof(stream_dest));
    }
}

// --- Main Audio Thread Hook -------------------------------------------------

// Called continuously with 48kHz samples from the RX processing chain.
// No filtering or decimation required; just gain and packetization.
//
// This is sound.c's copy of the IQ for the HPSDR/UDP stream only - it
// knows nothing about usb_gadget.c, which sound.c feeds separately from
// its own copy. A no-op whenever no Protocol 1 client is connected.
void hpsdr_send_iq(double *i_samples, double *q_samples, int n)
{
    if (!client_active || hpsdr_sock < 0) return;

    for (int k = 0; k < n; k++) {
        iq_buf_i[iq_buf_count] = i_samples[k] * hpsdr_iq_gain;
        iq_buf_q[iq_buf_count] = q_samples[k] * hpsdr_iq_gain;
        iq_buf_count++;

        if (iq_buf_count >= SAMPLES_PER_PACKET) {
            build_and_send_packet();
            iq_buf_count = 0;
        }
    }
}

// --- Command and Discovery (Background Thread) ------------------------------

static void handle_command(uint8_t *buf, int len, struct sockaddr_in *sender)
{
    // Frequency control used to be parsed out of the inbound EP2 stream
    // here (C0 address 2 carried live RX frequency from every client
    // tested) and applied via remote_execute()/radio_tune_to(). That was
    // fragile - SDR Console, for one, sends zero packets of any kind
    // between the initial connect burst and a disconnect/reconnect, so it
    // never delivered a live retune this way - and once hamlib.c came
    // online it meant two control surfaces that could race each other to
    // set frequency. Live frequency control now lives exclusively in
    // hamlib.c's rigctld-compatible "F" command; this file no longer
    // touches freq_hdr except to report it back as outbound telemetry
    // (see build_and_send_packet()).

    if (len < 4) return;
    if (buf[0] != 0xEF || buf[1] != 0xFE) return;

    switch (buf[2]) {
    case 0x02:  // Discovery request
        {
            uint8_t reply[64];
            memset(reply, 0, sizeof(reply));

            reply[0] = 0xEF;
            reply[1] = 0xFE;
            reply[2] = 0x02;

            // 0x00 = available, 0x02 = in-use by another client
            int same_client =
                (client_active &&
                 sender->sin_addr.s_addr == stream_dest.sin_addr.s_addr &&
                 sender->sin_port        == stream_dest.sin_port);

            reply[3] = (client_active && !same_client) ? 0x02 : 0x00;

            // MAC + board/protocol identifiers (keep your current values for now)
            reply[4]  = 0x00; reply[5]  = 0x1C; reply[6]  = 0xC0;
            reply[7]  = 0xA2; reply[8]  = 0x22; reply[9]  = 0x5B;
            // Board type: 0x06 (the prior value here) isn't a real HPSDR
            // board ID - the recognized set is 0x11 Metis, 0x22 Hermes,
            // 0x33 Griffin, 0x44 Angelia, 0x55 Orion, 0x66 Orion2,
            // 0x77 Hermes Lite, 0x88 Hermes Lite2, 0x99 C25/RedPitaya.
            // Sending an unrecognized ID likely made clients fall back to
            // some default profile instead of treating minibitx as the
            // narrow (~48kHz), single-ADC board it actually is - possibly
            // why SDR Console isn't sending retunes for nearby frequency
            // changes (it may assume a much wider tunable passband).
            // Hermes Lite2 is the closest honest match in spirit (lean,
            // minimal, single-ADC), so declare that instead.
            reply[10] = 0x88; // board type: Hermes Lite2
            reply[11] = 0x25; // protocol version

            sendto(hpsdr_sock, reply, sizeof(reply), 0,
                   (struct sockaddr *)sender, sizeof(*sender));
        }
        break;

    case 0x04:  // Start / stop streaming
        {
            int start = ((buf[3] & 0x01) != 0) || (buf[3] != 0x00);
        
            if (start) {
                int same_dest =
                    client_active &&
                    sender->sin_addr.s_addr == stream_dest.sin_addr.s_addr &&
                    sender->sin_port        == stream_dest.sin_port;

                // Reply to the sender's actual address:port, not a hardcoded
                // HPSDR_PORT. That earlier "force 1024" was wrong: 1024 is
                // where clients SEND commands to us, but they RECEIVE the
                // EP6 IQ stream on the ephemeral port their own socket is
                // bound to (the same port sender came from here) - almost
                // always a different port than 1024. Forcing 1024 sent
                // every IQ packet to a port nothing was listening on: no
                // error (UDP sendto doesn't fail just because nobody's
                // listening), just silently discarded IQ while the client
                // sat there having successfully "started" a stream that
                // never arrived. See src/hpsdr_p1.c in drexjj/sbitx (the
                // known-working baseline this was ported from), which
                // never overrides the port here.
                if (!same_dest) {
                    stream_dest = *sender;
                    tx_seq = 0;
                    iq_buf_count = 0;
                    printf("hpsdr: streaming STARTED cmd=%u to %s:%d\n",
                           (unsigned)buf[3], inet_ntoa(stream_dest.sin_addr), ntohs(stream_dest.sin_port));
                } else {
                    // repeated START from same client: keep streaming, do not reset seq/buffer
                    stream_dest = *sender;   // refresh anyway
                }

                client_active = 1;
            } else {
                client_active = 0;
                printf("hpsdr: streaming STOPPED cmd=%u\n", (unsigned)buf[3]);
            }
        }
        break;

    case 0x01:  // EP2 host commands
        {
            // Accept full 1032-byte packet, but also parse shorter packets that still contain one frame.
            if (len < 16) break; // not enough for header + sync + c0 + data

            int frames_available = 0;
            if (len >= 8 + 512 + 512) frames_available = 2;
            else if (len >= 8 + 512)  frames_available = 1;
            else                       frames_available = 0;

            for (int frame = 0; frame < frames_available; frame++) {
                uint8_t *fp = buf + 8 + frame * 512;
                if (fp[0] != 0x7F || fp[1] != 0x7F || fp[2] != 0x7F) continue;

                // MOX (PTT) is the only thing still read from this stream:
                // some SDR apps key PTT through bit 0 of C0 even while
                // using CAT (hamlib.c) for everything else. Edge-triggered
                // because this C&C byte arrives on every frame, but
                // radio_set_tx() drives GPIO with settling delays, so only
                // call it when the requested state actually changes.
                int want_tx = (fp[3] & 0x01) ? 1 : 0;
                if (want_tx != in_tx)
                    radio_set_tx(want_tx);
            }
        }
        break;

    default:
        break;
    }
}

static void *hpsdr_poll_thread(void *arg)
{
    uint8_t buf[2048];
    struct sockaddr_in sender;
    socklen_t sender_len;

    while (running) {
        sender_len = sizeof(sender);
        int n = recvfrom(hpsdr_sock, buf, sizeof(buf), 0,
                         (struct sockaddr *)&sender, &sender_len);
        if (n > 0) {
            handle_command(buf, n, &sender);
        }
    }
    return NULL;
}

// --- Initialization API -----------------------------------------------------

int hpsdr_init(void)
{
    hpsdr_sock = socket(AF_INET, SOCK_DGRAM, 0);
    if (hpsdr_sock < 0) return -1;

    int optval = 1;
    setsockopt(hpsdr_sock, SOL_SOCKET, SO_REUSEADDR, &optval, sizeof(optval));
    setsockopt(hpsdr_sock, SOL_SOCKET, SO_BROADCAST, &optval, sizeof(optval));

    struct sockaddr_in addr;
    memset(&addr, 0, sizeof(addr));
    addr.sin_family = AF_INET;
    addr.sin_port = htons(HPSDR_PORT);
    addr.sin_addr.s_addr = htonl(INADDR_ANY);

    if (bind(hpsdr_sock, (struct sockaddr *)&addr, sizeof(addr)) < 0) {
        close(hpsdr_sock);
        hpsdr_sock = -1;
        return -1;
    }

    struct timeval tv = { .tv_sec = 0, .tv_usec = 200000 };
    setsockopt(hpsdr_sock, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv));

    running = 1;
    return 0;
}

void hpsdr_stop(void)
{
    running = 0;
    client_active = 0;
    
    if (hpsdr_sock >= 0) {
        close(hpsdr_sock);
        hpsdr_sock = -1;
    }
}

int hpsdr_is_connected(void)
{
    return client_active;
}

void hpsdr_poll(void)
{
    static int started = 0;
    if (!started && running) {
        pthread_create(&poll_thread, NULL, hpsdr_poll_thread, NULL);
        started = 1;
    }
}
